import dynamic from "next/dynamic";
import Head from "next/head";

//Components
import TopStatus from "../components/status/TopStatus";
import SideBar from "../components/sidebar/SideBar";

// Map
const MyAwesomeMap = dynamic(() => import("../components/map/Map"), {
  ssr: false,
});

export default function Home() {
  return (
    <div className="flex gap-1">
      <Head>
        <title>Covid-19</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SideBar />
      <main>
        <TopStatus />
        <MyAwesomeMap />
      </main>
    </div>
  );
}
